import { Meeting, SummaryTemplate } from '../types';
import { formatSeconds, formatDateTime } from './formatters';

/**
 * Generates an executive Markdown document of the meeting
 */
export function generateMeetingMarkdown(meeting: Meeting, template: SummaryTemplate = 'general'): string {
  const summary = meeting.summaries[template] || meeting.summaries.general;
  const dateStr = formatDateTime(meeting.date);

  const lines: string[] = [];

  lines.push(`# ${meeting.title}`);
  lines.push(`**Date**: ${dateStr}  `);
  lines.push(`**Duration**: ${meeting.durationMinutes} minutes  `);
  lines.push(`**Status**: ${meeting.status.toUpperCase()}  `);
  if (meeting.location) {
    lines.push(`**Location**: ${meeting.location}  `);
  }
  lines.push(`\n---\n`);

  lines.push(`## 1. Executive Summary (${template.toUpperCase()} Perspective)`);
  lines.push(summary.overview.trim());
  lines.push('');

  lines.push(`## 2. Key Discussion Topics`);
  summary.keyTopics.forEach((topic) => {
    lines.push(`### ${topic.title}`);
    topic.notes.forEach((note) => {
      lines.push(`- ${note}`);
    });
    lines.push('');
  });

  lines.push(`## 3. Decisions Log`);
  if (meeting.decisions.length === 0) {
    lines.push(`*No formal decisions logged.*`);
  } else {
    meeting.decisions.forEach((d, idx) => {
      lines.push(`${idx + 1}. **${d.title}** (${d.category.toUpperCase()})`);
      lines.push(`   - ${d.description}`);
      lines.push(`   - *Decided by*: ${d.decidedBy} at ${formatSeconds(d.timestampSeconds)}`);
    });
  }
  lines.push('');

  lines.push(`## 4. Action Items & Commitments`);
  if (meeting.actionItems.length === 0) {
    lines.push(`*No action items created.*`);
  } else {
    meeting.actionItems.forEach((a) => {
      lines.push(`- [${a.completed ? 'x' : ' '}] **${a.description}**`);
      lines.push(`  - Assignee: @${a.assigneeName} · Due: ${a.dueDate}`);
    });
  }
  lines.push('');

  lines.push(`## 5. Key Highlights`);
  if (meeting.highlights.length === 0) {
    lines.push(`*No highlights marked.*`);
  } else {
    meeting.highlights.forEach((h) => {
      lines.push(`> "${h.excerpt}"`);
      lines.push(`> — **${h.speakerName}** at ${formatSeconds(h.timestampSeconds)} (*${h.title}*)\n`);
    });
  }

  lines.push(`## 6. Complete Dialogue Transcript`);
  if (meeting.transcript.length === 0) {
    lines.push(`*Transcript pending recording processing.*`);
  } else {
    meeting.transcript.forEach((turn) => {
      lines.push(`**[${formatSeconds(turn.startTime)}] ${turn.speakerName}**:`);
      lines.push(`${turn.text}\n`);
    });
  }

  lines.push(`---\n*Generated by Fanthom AI — Executive Meeting Intelligence*`);

  return lines.join('\n');
}

/**
 * Generates a clean JSON export of the entire meeting artifact
 */
export function generateMeetingJson(meeting: Meeting): string {
  return JSON.stringify(meeting, null, 2);
}

/**
 * Triggers a browser file download with appropriate MIME type
 */
export function triggerBrowserDownload(filename: string, content: string, mimeType = 'text/markdown;charset=utf-8') {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
